name: Update Website

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  BUCKET_NAME: "s6qweasdzxc-hsbtg6"
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    name: Deploy to Website
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::854755582447:role/githubaction_terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync website with S3 bucket
        run: |
          aws s3 sync ./static/html s3://${{ env.BUCKET_NAME }}/ --delete

      - name: Make S3 objects public
        run: |
          aws s3 ls s3://${{ env.BUCKET_NAME }} --recursive | while read -r line; do
            key=$(echo $line | awk '{$1=$2=""; print $0}' | xargs)
            aws s3api put-object-acl --bucket ${{ env.BUCKET_NAME }} --key $key --acl public-read
          done
